#!/bin/bash
#
# vim-anywhere - use Vim whenever, wherever
# Author: Chris Knadler
# Homepage: https://www.github.com/cknadler/vim-anywhere
#
# Open a temporary file with Vim. Once Vim is closed, copy the contents of that
# file to the system clipboard.
# 
# Modified by Jesús Pérez to use terminal neovim and work only on linux

while getopts ":cv" opt; do
  case "$opt" in
    v) set -x ;;
    c) read_clipboard='true' ;;
    \?) echo "Invalid option: -$OPTARG" >&2 ;;
  esac
done

TERMINAL='kitty'
TMPFILE_DIR=/tmp/vim-anywhere
TMPFILE=$TMPFILE_DIR/doc-$(date +"%y%m%d%H%M%S")

mkdir -p $TMPFILE_DIR
touch $TMPFILE

chmod o-r $TMPFILE # Make file only readable by you

if [[ $read_clipboard == 'true' ]]; then
    xclip -o -selection clipboard > $TMPFILE
fi

$TERMINAL -e nvim $TMPFILE

cat $TMPFILE | xclip -selection clipboard
