#!/bin/bash
#
# vim-anywhere - use Vim whenever, wherever
# Author: Chris Knadler
# Homepage: https://www.github.com/cknadler/vim-anywhere
#
# Open a temporary file with Vim. Once Vim is closed, copy the contents of that
# file to the system clipboard.
# 
# Modified by Jesús Pérez to use terminal neovim and work only on linux

while getopts ":cv" opt; do
  case "$opt" in
    v) set -x ;;
    c) read_clipboard='true' ;;
    \?) echo "Invalid option: -$OPTARG" >&2 ;;
  esac
done

TERMINAL='kitty'
TMPFILE_DIR="$(mktemp -d /tmp/vim-anywhere.XXX)"
TMPFILE_TEMPLATE=doc-$(date +"%y%m%d%H%M%S").XXX

mkdir -p $TMPFILE_DIR
TMPFILE="$(mktemp -p $TMPFILE_DIR -t $TMPFILE_TEMPLATE)"

remove_tmp_dir() {
    rm -rf $TMPFILE_DIR
}

# Remove all temp files on exit and sigint
trap "remove_tmp_dir" EXIT SIGINT

# Launch vim
if [[ $read_clipboard == 'true' ]]; then
    xclip -o -selection clipboard > $TMPFILE
    $TERMINAL -e nvim $TMPFILE
else
    $TERMINAL -e nvim $TMPFILE +startinsert
fi

# Copy the content to the clipboard
cat $TMPFILE | xclip -selection clipboard

# Automatically paste after closing
xdotool key --delay 100 ctrl+v
